#!/usr/bin/env bash
set -e

mkdir -p /etc/ceph
echo 'Running ceph demo cluster'
docker run -d --name $BACKEND_NAME --net=host -v /etc/ceph:/etc/ceph -v /lib/modules:/lib/modules -e MON_IP=$HOST_IP -e CEPH_PUBLIC_NETWORK=0.0.0.0/0 -e DEMO_DAEMONS='osd mds' ceph/daemon:latest-mimic demo

# Wait until the ceph config file exists
echo 'Waiting for ceph config file to be ready'
while [ ! -f /etc/ceph/ceph.conf ]; do
          sleep 1
done
sleep 1

# Change Ceph default features
sed -i 's/\[global\]/[global]\nrbd default features = 3/' /etc/ceph/ceph.conf

# Create the tar file with the ceph config and credentials
sudo tar -cvf --directory=/ `pwd`/files.tar etc/ceph
sudo chown `whoami`:`whoami` files.tar
